//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA2022._02._21.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFA2022._02._21.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1200px_Refresh_icon_svg {
            get {
                object obj = ResourceManager.GetObject("_1200px_Refresh_icon_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _167130 {
            get {
                object obj = ResourceManager.GetObject("_167130", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5940432 {
            get {
                object obj = ResourceManager.GetObject("_5940432", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] C__beadando_14ESZ1_2 {
            get {
                object obj = ResourceManager.GetObject("C__beadando_14ESZ1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tanverseny (azonosito, versenynev, tipus, esemeny, datum) VALUES
        ///(1,&apos;Magyar irodalom&apos;,&apos;OKTV&apos;,&apos;Nevezés&apos;,&apos;2004.10.1&apos;),
        ///(2,&apos;Magyar nyelv&apos;,&apos;OKTV&apos;,&apos;Nevezés&apos;,&apos;2004.10.1&apos;),
        ///(3,&apos;Történelem&apos;,&apos;OKTV&apos;,&apos;Nevezés&apos;,&apos;2004.10.1&apos;),
        ///(4,&apos;Földrajz&apos;,&apos;OKTV&apos;,&apos;Nevezés&apos;,&apos;2004.10.1&apos;),
        ///(5,&apos;Angol nyelv&apos;,&apos;OKTV&apos;,&apos;Nevezés&apos;,&apos;2004.10.1&apos;),
        ///(6,&apos;Francia nyelv I. kategória&apos;,&apos;OKTV&apos;,&apos;Nevezés&apos;,&apos;2004.10.1&apos;),
        ///(7,&apos;Francia nyelv II. kategória&apos;,&apos;OKTV&apos;,&apos;Nevezés&apos;,&apos;2004.10.1&apos;),
        ///(8,&apos;Német nyelv I. kategória&apos;,&apos;OKTV&apos;,&apos;Nevezés&apos;,&apos;2004.10.1&apos;) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tanScript {
            get {
                return ResourceManager.GetString("tanScript", resourceCulture);
            }
        }
    }
}
